### ISSUE TITLE
ChatError: Failed to parse response: {"type":"status","status":"started"}

### ISSUE THREAD

**Issue by samedovzaur** [dataprofessor/hugchat#6]
It gives the same error although code is correct for sure checked couple of times.

**Comment by hpsc3** [comment]
Yes, started happening today. Was working fine before.

**Comment by samedovzaur** [comment]
I made it work like 10 mins before this error but it still gives the error I think it is something related to hf login process cuz there is not any wrong thing in the code(As I assume)

**Comment by AravindRohit** [comment]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/hugchat/hugchat.py", line 263, in chat
    obj = json.loads(res[1:-1])
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 7 (char 6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "solr2.py", line 157, in <module>
    result = call_nlp_api(url, subject, standard_level, searchinput, email, passwd)
  File "solr2.py", line 9, in call_nlp_api
    chat_response = start_chat_with_bot(email, passwd, searchinput)
  File "solr2.py", line 146, in start_chat_with_bot
    chat_response = start_chat(email, passwd, input_text)
  File "solr2.py", line 132, in start_chat
    use_cache=True  # Enable response caching
  File "/home/ubuntu/.local/lib/python3.6/site-packages/hugchat/hugchat.py", line 267, in chat
    raise ChatError(f"Failed to parse response: {res}")
hugchat.exceptions.ChatError: Failed to parse response: {"type":"status","status":"started"}

**Comment by AravindRohit** [comment]
For me it is getting this error from yesterday but my code is correct from yesterday only it is getting error how to solve this

**Comment by AravindRohit** [comment]
Sir, Please tell me how to fix this?

**Comment by AravindRohit** [comment]
> Yes, started happening today. Was working fine before.

Yes, from yesterday is giving error how to fix this sir

**Comment by samedovzaur** [comment]
> Sir, Please tell me how to fix this?

I have not solved it yet sir! (swithced to openai & llama 2. again)

**Comment by AravindRohit** [comment]
> > Sir, Please tell me how to fix this?
> 
> I have not solved it yet sir! (swithced to openai & llama 2. again)

Okay sir

**Comment by AravindRohit** [comment]
When you will be able to fix this sir?
